### ISSUE TITLE
Demo 中 切换NetType.Http后Client就无法访问了是什么原因呢

### ISSUE THREAD

**Issue by happygb21-jc** [NewLifeX/NewLife.Remoting#2]
var netUri = new NetUri(NetType.Http, IPAddress.Any, 5001);
    
     var client = new MyClient("http://127.0.0.1:5001")
     这样是对的吗

**Comment by nnhy** [comment]
服务端ApiServer不支持用http，无法识别。
ApiServer直接用tcp好了，主要提供rpc服务，同时可以支持http访问，性能要低一些。

**Comment by happygb21-jc** [comment]
> 服务端ApiServer不支持用http，无法识别。 ApiServer直接用tcp好了，主要提供rpc服务，同时可以支持http访问，性能要低一些。

谢谢
